version: '3.8'

services:
  nginx:
    image: ghcr.io/ai-cfia/nginx:0.0.4
    container_name: fertiscan-frontend-nginx
    restart: always
    ports:
      - "80:80"
    environment:
      - BACKEND_PORT=5000 # Needs to point to the internal port of the backend service (5000)
      - FRONTEND_PORT=3000 # Needs to point to the internal port of the frontend service (3000)
      - SWAGGER_PATH=swagger # Use anything but '/api' to avoid conflicts with the backend. Make sure to use the same value for API_BASE_PATH in the backend. e.g. 'API_BASE_PATH=/swagger'
    depends_on:
      - frontend
      - backend
    networks:
      - fertiscan-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fertiscan-frontend
    restart: always
    ports:
      - "3000:3000" # if you want to run the frontend on a different port, change the first port number
    depends_on:
      - postgres
    networks:
      - fertiscan-network

  backend:
    image: ghcr.io/ai-cfia/fertiscan-backend:main
    container_name: fertiscan-backend
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "5001:5000" # if you want to run the backend on a different port, change the first port number
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - fertiscan-network

  postgres:
    image: ghcr.io/ai-cfia/postgres:0.0.5
    container_name: fertiscan-frontend-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fertiscan
      - BB_URL=${BB_URL}
      - PROJECT_NAME=fertiscan
      - BB_SERVICE_ACCOUNT=${BB_SERVICE_ACCOUNT}
      - BB_SERVICE_KEY=${BB_SERVICE_KEY}
      - INSTANCE_ID=${BB_INSTANCE_ID}
      - DATABASE_ID=${BB_DATABASE_ID}
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 10s
      retries: 5
    networks:
      - fertiscan-network
    volumes:
      - fertiscan-frontend-postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: fertiscan-frontend-pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    volumes:
      - fertiscan-frontend-pgadmin:/var/lib/pgadmin
    networks:
      - fertiscan-network
    depends_on:
      - postgres

networks:
  fertiscan-network:
    driver: bridge

volumes:
  fertiscan-frontend-postgres-data:
  fertiscan-frontend-pgadmin:
