/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Nutrient } from "./nutrient";

/**
 *
 * @export
 * @interface AppModelsLabelDataGuaranteedAnalysis
 */
export interface AppModelsLabelDataGuaranteedAnalysis {
  /**
   *
   * @type {string}
   * @memberof AppModelsLabelDataGuaranteedAnalysis
   */
  title?: string | null;
  /**
   *
   * @type {Array<Nutrient>}
   * @memberof AppModelsLabelDataGuaranteedAnalysis
   */
  nutrients?: Array<Nutrient>;
  /**
   *
   * @type {boolean}
   * @memberof AppModelsLabelDataGuaranteedAnalysis
   */
  is_minimal?: boolean | null;
}
