/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AuditTrail
 */
export interface AuditTrail {
  /**
   *
   * @type {string}
   * @memberof AuditTrail
   */
  upload_date: string;
  /**
   *
   * @type {string}
   * @memberof AuditTrail
   */
  edited_by: string;
  /**
   *
   * @type {string}
   * @memberof AuditTrail
   */
  edit_date: string;
  /**
   *
   * @type {string}
   * @memberof AuditTrail
   */
  change_log: string;
  /**
   *
   * @type {string}
   * @memberof AuditTrail
   */
  access_log: string;
  /**
   *
   * @type {boolean}
   * @memberof AuditTrail
   */
  privacy_flag: boolean;
}
