/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { FolderMetadata } from "./folder-metadata";

/**
 *
 * @export
 * @interface DeleteFolderResponse
 */
export interface DeleteFolderResponse {
  /**
   *
   * @type {string}
   * @memberof DeleteFolderResponse
   */
  id: string;
  /**
   *
   * @type {FolderMetadata}
   * @memberof DeleteFolderResponse
   */
  metadata?: FolderMetadata | null;
  /**
   *
   * @type {string}
   * @memberof DeleteFolderResponse
   */
  owner_id?: string | null;
  /**
   *
   * @type {string}
   * @memberof DeleteFolderResponse
   */
  upload_date?: string | null;
  /**
   *
   * @type {string}
   * @memberof DeleteFolderResponse
   */
  name?: string | null;
  /**
   *
   * @type {Array<string>}
   * @memberof DeleteFolderResponse
   */
  file_ids?: Array<string> | null;
  /**
   *
   * @type {boolean}
   * @memberof DeleteFolderResponse
   */
  deleted?: boolean;
}
