/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface FertiscanDbMetadataInspectionRegistrationNumber
 */
export interface FertiscanDbMetadataInspectionRegistrationNumber {
  /**
   *
   * @type {string}
   * @memberof FertiscanDbMetadataInspectionRegistrationNumber
   */
  registration_number?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof FertiscanDbMetadataInspectionRegistrationNumber
   */
  is_an_ingredient?: boolean | null;
  /**
   *
   * @type {boolean}
   * @memberof FertiscanDbMetadataInspectionRegistrationNumber
   */
  edited?: boolean | null;
}
