/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { FertiscanDbMetadataInspectionValue } from "./fertiscan-db-metadata-inspection-value";
// May contain unused imports in some cases
// @ts-ignore
import type { Title } from "./title";

/**
 *
 * @export
 * @interface FertiscanDbMetadataInspectionGuaranteedAnalysis
 */
export interface FertiscanDbMetadataInspectionGuaranteedAnalysis {
  /**
   *
   * @type {Title}
   * @memberof FertiscanDbMetadataInspectionGuaranteedAnalysis
   */
  title?: Title | null;
  /**
   *
   * @type {boolean}
   * @memberof FertiscanDbMetadataInspectionGuaranteedAnalysis
   */
  is_minimal?: boolean | null;
  /**
   *
   * @type {Array<FertiscanDbMetadataInspectionValue>}
   * @memberof FertiscanDbMetadataInspectionGuaranteedAnalysis
   */
  en?: Array<FertiscanDbMetadataInspectionValue>;
  /**
   *
   * @type {Array<FertiscanDbMetadataInspectionValue>}
   * @memberof FertiscanDbMetadataInspectionGuaranteedAnalysis
   */
  fr?: Array<FertiscanDbMetadataInspectionValue>;
}
