/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AppModelsLabelDataGuaranteedAnalysis } from "./app-models-label-data-guaranteed-analysis";
// May contain unused imports in some cases
// @ts-ignore
import type { Nutrient } from "./nutrient";
// May contain unused imports in some cases
// @ts-ignore
import type { Organization } from "./organization";
// May contain unused imports in some cases
// @ts-ignore
import type { Quantity } from "./quantity";
// May contain unused imports in some cases
// @ts-ignore
import type { RegistrationNumber } from "./registration-number";

/**
 *
 * @export
 * @interface InspectionCreate
 */
export interface InspectionCreate {
  /**
   *
   * @type {Array<Organization>}
   * @memberof InspectionCreate
   */
  organizations?: Array<Organization>;
  /**
   *
   * @type {string}
   * @memberof InspectionCreate
   */
  fertiliser_name?: string | null;
  /**
   *
   * @type {Array<RegistrationNumber>}
   * @memberof InspectionCreate
   */
  registration_number?: Array<RegistrationNumber>;
  /**
   *
   * @type {string}
   * @memberof InspectionCreate
   */
  lot_number?: string | null;
  /**
   *
   * @type {Array<Quantity>}
   * @memberof InspectionCreate
   */
  weight?: Array<Quantity>;
  /**
   *
   * @type {Quantity}
   * @memberof InspectionCreate
   */
  density?: Quantity | null;
  /**
   *
   * @type {Quantity}
   * @memberof InspectionCreate
   */
  volume?: Quantity | null;
  /**
   *
   * @type {string}
   * @memberof InspectionCreate
   */
  npk?: string | null;
  /**
   *
   * @type {AppModelsLabelDataGuaranteedAnalysis}
   * @memberof InspectionCreate
   */
  guaranteed_analysis_en?: AppModelsLabelDataGuaranteedAnalysis | null;
  /**
   *
   * @type {AppModelsLabelDataGuaranteedAnalysis}
   * @memberof InspectionCreate
   */
  guaranteed_analysis_fr?: AppModelsLabelDataGuaranteedAnalysis | null;
  /**
   *
   * @type {Array<string>}
   * @memberof InspectionCreate
   */
  cautions_en?: Array<string> | null;
  /**
   *
   * @type {Array<string>}
   * @memberof InspectionCreate
   */
  cautions_fr?: Array<string> | null;
  /**
   *
   * @type {Array<string>}
   * @memberof InspectionCreate
   */
  instructions_en?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof InspectionCreate
   */
  instructions_fr?: Array<string>;
  /**
   *
   * @type {Array<Nutrient>}
   * @memberof InspectionCreate
   */
  ingredients_en?: Array<Nutrient>;
  /**
   *
   * @type {Array<Nutrient>}
   * @memberof InspectionCreate
   */
  ingredients_fr?: Array<Nutrient>;
  /**
   *
   * @type {string}
   * @memberof InspectionCreate
   */
  picture_set_id: string;
}
