/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { FertiscanDbMetadataInspectionGuaranteedAnalysis } from "./fertiscan-db-metadata-inspection-guaranteed-analysis";
// May contain unused imports in some cases
// @ts-ignore
import type { OrganizationInformation } from "./organization-information";
// May contain unused imports in some cases
// @ts-ignore
import type { ProductInformationOutput } from "./product-information-output";
// May contain unused imports in some cases
// @ts-ignore
import type { SubLabel } from "./sub-label";
// May contain unused imports in some cases
// @ts-ignore
import type { ValuesObjects } from "./values-objects";

/**
 *
 * @export
 * @interface InspectionResponse
 */
export interface InspectionResponse {
  /**
   *
   * @type {string}
   * @memberof InspectionResponse
   */
  inspection_id: string;
  /**
   *
   * @type {string}
   * @memberof InspectionResponse
   */
  inspector_id?: string | null;
  /**
   *
   * @type {string}
   * @memberof InspectionResponse
   */
  inspection_comment?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof InspectionResponse
   */
  verified?: boolean | null;
  /**
   *
   * @type {Array<OrganizationInformation>}
   * @memberof InspectionResponse
   */
  organizations?: Array<OrganizationInformation> | null;
  /**
   *
   * @type {ProductInformationOutput}
   * @memberof InspectionResponse
   */
  product: ProductInformationOutput;
  /**
   *
   * @type {SubLabel}
   * @memberof InspectionResponse
   */
  cautions: SubLabel;
  /**
   *
   * @type {SubLabel}
   * @memberof InspectionResponse
   */
  instructions: SubLabel;
  /**
   *
   * @type {FertiscanDbMetadataInspectionGuaranteedAnalysis}
   * @memberof InspectionResponse
   */
  guaranteed_analysis: FertiscanDbMetadataInspectionGuaranteedAnalysis;
  /**
   *
   * @type {ValuesObjects}
   * @memberof InspectionResponse
   */
  ingredients: ValuesObjects;
}
