/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { NutrientValue } from "./nutrient-value";
// May contain unused imports in some cases
// @ts-ignore
import type { Organization } from "./organization";
// May contain unused imports in some cases
// @ts-ignore
import type { PipelineInspectionGuaranteedAnalysis } from "./pipeline-inspection-guaranteed-analysis";
// May contain unused imports in some cases
// @ts-ignore
import type { PipelineInspectionRegistrationNumber } from "./pipeline-inspection-registration-number";
// May contain unused imports in some cases
// @ts-ignore
import type { PipelineInspectionValue } from "./pipeline-inspection-value";

/**
 *
 * @export
 * @interface LabelDataInput
 */
export interface LabelDataInput {
  /**
   *
   * @type {Array<Organization>}
   * @memberof LabelDataInput
   */
  organizations?: Array<Organization>;
  /**
   *
   * @type {string}
   * @memberof LabelDataInput
   */
  fertiliser_name?: string | null;
  /**
   *
   * @type {Array<PipelineInspectionRegistrationNumber>}
   * @memberof LabelDataInput
   */
  registration_number?: Array<PipelineInspectionRegistrationNumber>;
  /**
   *
   * @type {string}
   * @memberof LabelDataInput
   */
  lot_number?: string | null;
  /**
   *
   * @type {Array<PipelineInspectionValue>}
   * @memberof LabelDataInput
   */
  weight?: Array<PipelineInspectionValue>;
  /**
   *
   * @type {PipelineInspectionValue}
   * @memberof LabelDataInput
   */
  density?: PipelineInspectionValue | null;
  /**
   *
   * @type {PipelineInspectionValue}
   * @memberof LabelDataInput
   */
  volume?: PipelineInspectionValue | null;
  /**
   *
   * @type {string}
   * @memberof LabelDataInput
   */
  npk?: string | null;
  /**
   *
   * @type {PipelineInspectionGuaranteedAnalysis}
   * @memberof LabelDataInput
   */
  guaranteed_analysis_en?: PipelineInspectionGuaranteedAnalysis | null;
  /**
   *
   * @type {PipelineInspectionGuaranteedAnalysis}
   * @memberof LabelDataInput
   */
  guaranteed_analysis_fr?: PipelineInspectionGuaranteedAnalysis | null;
  /**
   *
   * @type {Array<string>}
   * @memberof LabelDataInput
   */
  cautions_en?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof LabelDataInput
   */
  cautions_fr?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof LabelDataInput
   */
  instructions_en?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof LabelDataInput
   */
  instructions_fr?: Array<string>;
  /**
   *
   * @type {Array<NutrientValue>}
   * @memberof LabelDataInput
   */
  ingredients_en?: Array<NutrientValue>;
  /**
   *
   * @type {Array<NutrientValue>}
   * @memberof LabelDataInput
   */
  ingredients_fr?: Array<NutrientValue>;
}
