/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Organization
 */
export interface Organization {
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  name?: string | null;
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  address?: string | null;
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  website?: string | null;
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  phone_number?: string | null;
}
