/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PipelineInspectionRegistrationNumber
 */
export interface PipelineInspectionRegistrationNumber {
  /**
   *
   * @type {string}
   * @memberof PipelineInspectionRegistrationNumber
   */
  identifier: string | null;
  /**
   *
   * @type {string}
   * @memberof PipelineInspectionRegistrationNumber
   */
  type?: string | null;
}
