/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Metrics } from "./metrics";

/**
 *
 * @export
 * @interface ProductInformationOutput
 */
export interface ProductInformationOutput {
  /**
   *
   * @type {string}
   * @memberof ProductInformationOutput
   */
  name?: string | null;
  /**
   *
   * @type {string}
   * @memberof ProductInformationOutput
   */
  label_id?: string | null;
  /**
   *
   * @type {string}
   * @memberof ProductInformationOutput
   */
  registration_number?: string | null;
  /**
   *
   * @type {string}
   * @memberof ProductInformationOutput
   */
  lot_number?: string | null;
  /**
   *
   * @type {Metrics}
   * @memberof ProductInformationOutput
   */
  metrics?: Metrics | null;
  /**
   *
   * @type {string}
   * @memberof ProductInformationOutput
   */
  npk?: string | null;
  /**
   *
   * @type {string}
   * @memberof ProductInformationOutput
   */
  warranty?: string | null;
  /**
   *
   * @type {number}
   * @memberof ProductInformationOutput
   */
  n?: number | null;
  /**
   *
   * @type {number}
   * @memberof ProductInformationOutput
   */
  p?: number | null;
  /**
   *
   * @type {number}
   * @memberof ProductInformationOutput
   */
  k?: number | null;
}
