/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { RegistrationType } from "./registration-type";

/**
 *
 * @export
 * @interface RegistrationNumber
 */
export interface RegistrationNumber {
  /**
   *
   * @type {string}
   * @memberof RegistrationNumber
   */
  identifier?: string | null;
  /**
   *
   * @type {RegistrationType}
   * @memberof RegistrationNumber
   */
  type?: RegistrationType | null;
}
