/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Title
 */
export interface Title {
  /**
   *
   * @type {string}
   * @memberof Title
   */
  en?: string | null;
  /**
   *
   * @type {string}
   * @memberof Title
   */
  fr?: string | null;
}
