/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { FertiscanDbMetadataInspectionValue } from "./fertiscan-db-metadata-inspection-value";

/**
 *
 * @export
 * @interface ValuesObjects
 */
export interface ValuesObjects {
  /**
   *
   * @type {Array<FertiscanDbMetadataInspectionValue>}
   * @memberof ValuesObjects
   */
  en?: Array<FertiscanDbMetadataInspectionValue>;
  /**
   *
   * @type {Array<FertiscanDbMetadataInspectionValue>}
   * @memberof ValuesObjects
   */
  fr?: Array<FertiscanDbMetadataInspectionValue>;
}
