/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Value
 */
export interface Value {
  /**
   *
   * @type {number}
   * @memberof Value
   */
  value?: number | null;
  /**
   *
   * @type {string}
   * @memberof Value
   */
  unit?: string | null;
  /**
   *
   * @type {string}
   * @memberof Value
   */
  name?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof Value
   */
  edited?: boolean | null;
}
