name: Fertiscan frontend workflows

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:
  lint-test:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-lint-test-node.yml@main

  markdown-check:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-markdown-check.yml@main
    with:
      md-link-config-file-path: ".mlc_config.json"
    secrets: inherit

  repo-standard:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@main
    secrets: inherit

  build-and-push-gcr:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-build-push-container-github-registry.yml@main
    with:
      container-name: ${{ github.event.repository.name }}
      tag: ${{ github.sha }}
      registry: ghcr.io/ai-cfia
    secrets: inherit
    
  pr-labelling:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-pr-labelling.yml@main
    secrets: inherit
